[tool.black]
line-length = 88
exclude = "lep/transport/proto/"

[tool.isort]
profile = "black"
skip = ["lep/transport/proto/"]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = ["lep/transport/proto/"]