# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\rlep.transport\"`\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x05\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"2\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"\x8e\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\x05\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x05\x12\x15\n\rprev_log_term\x18\x04 \x01(\x05\x12\x0f\n\x07\x65ntries\x18\x05 \x03(\t\x12\x15\n\rleader_commit\x18\x06 \x01(\x05\",\n\tHeartbeat\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\x05\"1\n\x0eLeaderAnnounce\x12\x11\n\tleader_id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\"\x1d\n\x0b\x43oordinator\x12\x0e\n\x06leader\x18\x01 \x01(\x05\"\n\n\x08\x45lection\"\xa5\x01\n\x0e\x43ontrolMessage\x12\x34\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32$.lep.transport.ControlMessage.Action\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\"L\n\x06\x41\x63tion\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01\x12\t\n\x05\x43RASH\x10\x02\x12\x0b\n\x07RESTART\x10\x03\x12\t\n\x05PAUSE\x10\x04\x12\n\n\x06RESUME\x10\x05\x32\xd3\x03\n\x0eLeaderElection\x12\x46\n\x0bRequestVote\x12\x1a.lep.transport.VoteRequest\x1a\x1b.lep.transport.VoteResponse\x12Q\n\rAppendEntries\x12#.lep.transport.AppendEntriesRequest\x1a\x1b.lep.transport.VoteResponse\x12\x46\n\rSendHeartbeat\x12\x18.lep.transport.Heartbeat\x1a\x1b.lep.transport.VoteResponse\x12L\n\x0e\x41nnounceLeader\x12\x1d.lep.transport.LeaderAnnounce\x1a\x1b.lep.transport.VoteResponse\x12J\n\x0fSendCoordinator\x12\x1a.lep.transport.Coordinator\x1a\x1b.lep.transport.VoteResponse\x12\x44\n\x0cSendElection\x12\x17.lep.transport.Election\x1a\x1b.lep.transport.VoteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOTEREQUEST']._serialized_start=33
  _globals['_VOTEREQUEST']._serialized_end=129
  _globals['_VOTERESPONSE']._serialized_start=131
  _globals['_VOTERESPONSE']._serialized_end=181
  _globals['_APPENDENTRIESREQUEST']._serialized_start=184
  _globals['_APPENDENTRIESREQUEST']._serialized_end=326
  _globals['_HEARTBEAT']._serialized_start=328
  _globals['_HEARTBEAT']._serialized_end=372
  _globals['_LEADERANNOUNCE']._serialized_start=374
  _globals['_LEADERANNOUNCE']._serialized_end=423
  _globals['_COORDINATOR']._serialized_start=425
  _globals['_COORDINATOR']._serialized_end=454
  _globals['_ELECTION']._serialized_start=456
  _globals['_ELECTION']._serialized_end=466
  _globals['_CONTROLMESSAGE']._serialized_start=469
  _globals['_CONTROLMESSAGE']._serialized_end=634
  _globals['_CONTROLMESSAGE_ACTION']._serialized_start=558
  _globals['_CONTROLMESSAGE_ACTION']._serialized_end=634
  _globals['_LEADERELECTION']._serialized_start=637
  _globals['_LEADERELECTION']._serialized_end=1104
# @@protoc_insertion_point(module_scope)
